base_images:
  cli:
    name: "4.10"
    namespace: ocp
    tag: cli
binary_build_commands: make bin
build_root:
  project_image:
    dockerfile_path: .ci/openshift-ci/Dockerfile
images:
- context_dir: openshift-ci/build-root
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: oc-bin-image
releases:
  latest:
    release:
      architecture: amd64
      channel: stable
      version: "4.11"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: managed-gitops-e2e-tests
  steps:
    cluster_profile: aws
    test:
    - as: managed-gitops-e2e-step
      commands: scripts/openshiftci-presubmit-all-tests.sh
      from: oc-bin-image
      resources:
        requests:
          cpu: 100m
    workflow: ipi-aws
zz_generated_metadata:
  branch: openShiftCI
  org: redhat-appstudio
  repo: managed-gitops
